# -*- coding: utf-8 -*-
"""thresholding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P2sNa2EoIU3zZPfYgYe7yeSj51qSkIs8

##### **Program: threshold_analysis.py**
Project: Healthcare Stroke Risk Analysis

Author: Sophia L.
Last Updated: 2026-07-14

Purpose: Utility functions for selecting and evaluating probability classification thresholds based on recall requirements.

    Functions:
    threshold_analysis:
        Identify the highest probability threshold that achieves
        a desired recall level using cross-validated training
        predictions, then apply the selected threshold to new
        predicted probabilities.
"""

import numpy as np
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import (
    confusion_matrix,
    recall_score,
    precision_score,
    fbeta_score
)
def threshold_analysis(
    model,
    X_train,
    y_train,
    y_test,
    y_prob,
    cv,
    target_recall,
    step=0.01
):

  """
  Select a probability threshold that achieves the target recall.

  Uses out-of-fold cross-validated predicted probabilities from the training
  data to avoid selecting a threshold based on a single fitted model.

  Returns selected threshold, precision, recall, f2, the confusion matrix,
  and predicted classes.
  """

  # Generate out-of-fold predicted probabilities using cross-validation
  # These predictions simulate model performance on unseen data
  cv_prob = cross_val_predict(
     model,
     X_train,
     y_train,
     cv=cv,
     method="predict_proba",
     n_jobs=-1
 )[:,1] 
 
 # Create candidate thresholds. Searching high to low identifies the most 
 # conservative thresholds that meets the recall requirement
  thresholds = np.arange(1.0, 0.0, -step)
  
  selected_threshold = None
  
  # Select highest threshold achieving target recall
  
  for threshold in thresholds:
    # Convert probabilities into binary predictions based
    # on the current threshold
    threshold_pred = (cv_prob >= threshold).astype(int)
    
    # Stop searching once the target recall requirement is met
    if recall_score(y_train, threshold_pred) >= target_recall:
      selected_threshold = threshold
      break
    
  if selected_threshold is None:
    return None
      
  print(selected_threshold)
  
  # Apply selected threshold to test probabilities
  y_pred = (y_prob >= selected_threshold).astype(int)

  cm = confusion_matrix(y_test, y_pred)

  # Display summary metrics
  print(
      recall_score(y_test, y_pred),
      precision_score(y_test, y_pred),
      fbeta_score(y_test, y_pred, beta=2))
  
  # Summarize threshold performance
  return {
      'recall': recall_score(y_test, y_pred),
      'precision': precision_score(y_test, y_pred),
      'f2' : fbeta_score(y_test, y_pred, beta=2),
      'threshold': selected_threshold,
      'y_pred': y_pred,
      'cm': cm
  }
