# -*- coding: utf-8 -*-
"""hyperparameter_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzcwqGiE6SFhLPsBmpig-KjzRg6Sjn8z

##### **Program: hyperparameter_tuning.py**
Project: Healthcare Stroke Risk Analysis

Author: Sophia L.
Last Updated: 2026-07-14

Purpose: Utility functions for hyperparameter optimization using gridsearch cross-validation

    Functions:
    tune_model:
        Perform GridSearchCV, identify the best hyperparameter
        combination, and refit the best estimator on the full
        training dataset.
"""

# Load packages
import pandas as pd
from sklearn.model_selection import GridSearchCV

def tune_model(
    X_train,
    y_train,
    estimator,
    param_grid,
    cv,
    scoring,
    refit_metric,
    n_jobs
):

  """
  Perform hyperparameter optimization using GridSearchCV.

  Returns the fitted GridSearchCV object, cross-validation
  results, best estimator, best parameters, and best score.
  """

  # Configure an exhaustive grid search over all
  # specified hyperparameter combinations
  grid_search = GridSearchCV(
      estimator=estimator,
      param_grid=param_grid,
      cv=cv,
      scoring=scoring,
      refit=refit_metric,
      n_jobs=n_jobs
  )

  # Fit each candidate model using cross-validation
  # and refit the best-performing model on the full
  # training dataset using the selected refit metric
  grid_search.fit(X_train, y_train)

  results = pd.DataFrame(grid_search.cv_results_)

  # Display the optimal hyperparameter combination
  print(grid_search.best_params_)

  return {
        "grid_search": grid_search,
        "results": results,
        "best_model": grid_search.best_estimator_,
        "best_params": grid_search.best_params_,
        "best_cv_score": grid_search.best_score_
    }